import { Baranggay } from "@/interfaces";

export const BARANGGAYS: Baranggay[] = [
  "All",
  "Bagumbayan",
  "Bambang",
  "Calzada Tipas",
  "Central Bicutan",
  "Central Signal Village",
  "Cembo",
  "Comembo",
  "East Rembo",
  "Fort Bonifacio",
  "Hagonoy",
  "Ibayo Tipas",
  "Katuparan",
  "Ligid Tipas",
  "Lower Bicutan",
  "Maharlika Village",
  "Napindan",
  "New Lower Bicutan",
  "North Daang Hari",
  "North Signal Village",
  "Palingon Tipas",
  "Pembo",
  "Pinagsama",
  "Pitogo",
  "Post Proper Northside",
  "Post Proper Southside",
  "Rizal",
  "San Miguel",
  "Santa Ana",
  "South Cembo",
  "South Daang Hari",
  "South Signal Village",
  "Tanyag",
  "Tuktukan",
  "Ususan",
  "Upper Bicutan",
  "Wawa",
  "West Rembo",
  "Western Bicutan",
];
